Convert pathlib.Path to str explicitly
Passing pathlib.Path arguments to subprocess.Popen in Python 3.7 causes
the following error:

    TypeError: argument of type 'WindowsPath' is not iterable